export const DEFAULT_CATEGORIES = [
  { name: 'Bebidas', iconKey: 'bebidas' },
  { name: 'Hambúrgueres', iconKey: 'hamburgueres' },
  { name: 'Porções', iconKey: 'porcoes' },
  { name: 'Pastéis', iconKey: 'pasteis' },
  { name: 'Pizzas', iconKey: 'pizzas' },
  { name: 'Drinques', iconKey: 'drinques' },
  { name: 'Cervejas', iconKey: 'cervejas' },
  { name: 'Frutos do Mar', iconKey: 'frutos-do-mar' },
  { name: 'Carnes', iconKey: 'carnes' },
  { name: 'Saladas', iconKey: 'saladas' },
  { name: 'Japonês', iconKey: 'japones' },
  { name: 'Massas', iconKey: 'massas' },
  { name: 'Sobremesas', iconKey: 'sobremesas' },
  { name: 'Cafés', iconKey: 'cafes' },
  { name: 'Café da Manhã', iconKey: 'cafe-da-manha' },
  { name: 'Sanduíches', iconKey: 'sanduiches' },
  { name: 'Wraps', iconKey: 'wraps' },
  { name: 'Cachorro-quente', iconKey: 'cachorro-quente' },
  { name: 'Sopas', iconKey: 'sopas' },
  { name: 'Vegetariano', iconKey: 'vegetariano' },
  { name: 'Infantil', iconKey: 'infantil' },
  { name: 'Molhos', iconKey: 'molhos' },
  { name: 'Sem Glúten', iconKey: 'sem-gluten' },
  { name: 'Vegano', iconKey: 'vegano' },
  { name: 'Sucos', iconKey: 'sucos' },
  { name: 'Milk-shakes', iconKey: 'milk-shakes' },
  { name: 'Smoothies', iconKey: 'smoothies' },
  { name: 'Sorvetes', iconKey: 'sorvetes' },
  { name: 'Doces', iconKey: 'doces' },
  { name: 'Combos', iconKey: 'combos' },
]

export const DEFAULT_CATEGORY_ICON_KEYS = new Set(DEFAULT_CATEGORIES.map((category) => category.iconKey))
